### PR TITLE
Indentation

### PR DESCRIPTION
**Pull request by lennym**

### CODE REVIEW

**Comment by lennym** [comment]
Branches off #20 and #21.

**Comment by JoeChapman** [comment]
LGTM, have you linked this with a project?

**Comment by lennym** [comment]
Yes, all of these bits of work were done with firearms.

**Comment by lennym** [comment]
Also, if you look at [the diff with "ignore whitespace changes"](https://github.com/UKHomeOfficeForms/hof-template-mixins/pull/22/files?w=1) you'll see this isn't much of a change.

**Pull request merged**
